# Generated by Django 4.0 on 2022-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='in_game',
            field=models.BooleanField(default=False, verbose_name='in_game'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='games',
            field=models.IntegerField(default=0, verbose_name='games'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='wins'),
        ),
    ]
