# Generated by Django 4.0 on 2022-03-08 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('battle', '0002_gamer_in_game_alter_gamer_games_alter_gamer_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='in_lobby',
            field=models.BooleanField(default=False, verbose_name='in_lobby'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_move', models.BooleanField(default=1)),
                ('player2_move', models.BooleanField(default=0)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamer', to='battle.gamer')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battle.gamer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
