# Generated by Django 4.0 on 2022-03-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_gamer_in_lobby_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='room_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
